package formula;

/**
 * Created by Simone Calciolari on 04/08/15.
 */
public enum FormulaType {

	//TEMPORAL
	TEMPORAL_ACROSS_QUANTIFIED,
	TEMPORAL_DOUBLE_IMPL,
	TEMPORAL_IMPLICATION,
	TEMPORAL_OR,
	TEMPORAL_AND,
	TEMPORAL_NOT,
	TEMPORAL_WEAK_UNTIL,
	TEMPORAL_RELEASE,
	TEMPORAL_UNTIL,
	TEMPORAL_GLOBALLY,
	TEMPORAL_EVENTUALLY,
	TEMPORAL_NEXT,
	TEMPORAL_WEAK_NEXT,
	TEMPORAL_LTL_ATOM,

	//LOCAL
	LOCAL_QUANTIFIED,
	LOCAL_DOUBLE_IMPL,
	LOCAL_IMPLICATION,
	LOCAL_OR,
	LOCAL_AND,
	LOCAL_NOT,
	LOCAL_FOL_ATOM,
	LOCAL_EQUALITY,
	LOCAL_TRUE,
	LOCAL_FALSE

}
